# Generated by Django 5.2.1 on 2026-05-11 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreasIdosoReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(default='draft', max_length=20)),
                ('paefi_novos_casos', models.IntegerField(blank=True, default=0, null=True)),
                ('paefi_acomp_inicio', models.IntegerField(blank=True, default=0, null=True)),
                ('paefi_inseridos', models.IntegerField(blank=True, default=0, null=True)),
                ('paefi_desligados', models.IntegerField(blank=True, default=0, null=True)),
                ('paefi_bolsa_familia', models.IntegerField(blank=True, default=0, null=True)),
                ('paefi_bpc', models.IntegerField(blank=True, default=0, null=True)),
                ('paefi_substancias', models.IntegerField(blank=True, default=0, null=True)),
                ('violencia_fisica_atendidas_anterior', models.IntegerField(blank=True, default=0, null=True)),
                ('violencia_fisica_inseridos', models.IntegerField(blank=True, default=0, null=True)),
                ('violencia_fisica_desligados', models.IntegerField(blank=True, default=0, null=True)),
                ('violencia_fisica_total', models.IntegerField(blank=True, default=0, null=True)),
                ('abuso_sexual_atendidas_anterior', models.IntegerField(blank=True, default=0, null=True)),
                ('abuso_sexual_inseridos', models.IntegerField(blank=True, default=0, null=True)),
                ('abuso_sexual_desligados', models.IntegerField(blank=True, default=0, null=True)),
                ('abuso_sexual_total', models.IntegerField(blank=True, default=0, null=True)),
                ('exploracao_sexual_atendidas_anterior', models.IntegerField(blank=True, default=0, null=True)),
                ('exploracao_sexual_inseridos', models.IntegerField(blank=True, default=0, null=True)),
                ('exploracao_sexual_desligados', models.IntegerField(blank=True, default=0, null=True)),
                ('exploracao_sexual_total', models.IntegerField(blank=True, default=0, null=True)),
                ('negligencia_atendidas_anterior', models.IntegerField(blank=True, default=0, null=True)),
                ('negligencia_inseridos', models.IntegerField(blank=True, default=0, null=True)),
                ('negligencia_desligados', models.IntegerField(blank=True, default=0, null=True)),
                ('negligencia_total', models.IntegerField(blank=True, default=0, null=True)),
                ('exploracao_financeira_atendidas_anterior', models.IntegerField(blank=True, default=0, null=True)),
                ('exploracao_financeira_inseridos', models.IntegerField(blank=True, default=0, null=True)),
                ('exploracao_financeira_desligados', models.IntegerField(blank=True, default=0, null=True)),
                ('exploracao_financeira_total', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Relatorio CREAS Idoso',
                'verbose_name_plural': 'Relatorios CREAS Idoso',
                'db_table': 'creas_idoso_reports',
                'ordering': ['-year', '-month', '-updated_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreasPcdReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(default='draft', max_length=20)),
                ('def_violencia_fisica_atendidas_anterior', models.IntegerField(blank=True, default=0, null=True)),
                ('def_violencia_fisica_inseridos', models.IntegerField(blank=True, default=0, null=True)),
                ('def_violencia_fisica_desligados', models.IntegerField(blank=True, default=0, null=True)),
                ('def_violencia_fisica_total', models.IntegerField(blank=True, default=0, null=True)),
                ('def_abuso_sexual_atendidas_anterior', models.IntegerField(blank=True, default=0, null=True)),
                ('def_abuso_sexual_inseridos', models.IntegerField(blank=True, default=0, null=True)),
                ('def_abuso_sexual_desligados', models.IntegerField(blank=True, default=0, null=True)),
                ('def_abuso_sexual_total', models.IntegerField(blank=True, default=0, null=True)),
                ('def_exploracao_sexual_atendidas_anterior', models.IntegerField(blank=True, default=0, null=True)),
                ('def_exploracao_sexual_inseridos', models.IntegerField(blank=True, default=0, null=True)),
                ('def_exploracao_sexual_desligados', models.IntegerField(blank=True, default=0, null=True)),
                ('def_exploracao_sexual_total', models.IntegerField(blank=True, default=0, null=True)),
                ('def_negligencia_atendidas_anterior', models.IntegerField(blank=True, default=0, null=True)),
                ('def_negligencia_inseridos', models.IntegerField(blank=True, default=0, null=True)),
                ('def_negligencia_desligados', models.IntegerField(blank=True, default=0, null=True)),
                ('def_negligencia_total', models.IntegerField(blank=True, default=0, null=True)),
                ('def_exploracao_financeira_atendidas_anterior', models.IntegerField(blank=True, default=0, null=True)),
                ('def_exploracao_financeira_inseridos', models.IntegerField(blank=True, default=0, null=True)),
                ('def_exploracao_financeira_desligados', models.IntegerField(blank=True, default=0, null=True)),
                ('def_exploracao_financeira_total', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Relatorio CREAS PCD',
                'verbose_name_plural': 'Relatorios CREAS PCD',
                'db_table': 'creas_pcd_reports',
                'ordering': ['-year', '-month', '-updated_at'],
                'managed': False,
            },
        ),
    ]
