# Generated by Django 5.2.1 on 2026-05-11 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeaiCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('unit', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria CEAI',
                'verbose_name_plural': 'Categorias CEAI',
                'db_table': 'ceai_categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CeaiOficina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_name', models.TextField()),
                ('total_vacancies', models.IntegerField(default=0)),
                ('vacancies', models.IntegerField(default=0)),
                ('unit', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Oficina CEAI',
                'verbose_name_plural': 'Oficinas CEAI',
                'db_table': 'ceai_oficinas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('directorate_id', models.UUIDField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Submissão',
                'verbose_name_plural': 'Submissões',
                'db_table': 'submissions',
                'managed': False,
            },
        ),
    ]
