# Generated by Django 5.2.1 on 2026-05-07 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directorates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuario'), ('diretor', 'Diretor')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_directorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_profiles', to='directorates.directorate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='ProfileDirectorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_units', models.JSONField(blank=True, null=True)),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorates.directorate')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Vinculo perfil-diretoria',
                'verbose_name_plural': 'Vinculos perfil-diretoria',
                'unique_together': {('profile', 'directorate')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='directorates',
            field=models.ManyToManyField(related_name='profiles', through='accounts.ProfileDirectorate', to='directorates.directorate'),
        ),
    ]
