# Generated by Django 5.2.1 on 2026-05-07 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('report_type', models.CharField(blank=True, db_column='type', max_length=50)),
            ],
            options={
                'verbose_name': 'Relatorio diario',
                'verbose_name_plural': 'Relatorios diarios',
                'db_table': 'daily_reports',
                'ordering': ['-date', '-updated_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('sheet_config', models.JSONField(blank=True, null=True)),
                ('form_definition', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('available_units', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Diretoria',
                'verbose_name_plural': 'Diretorias',
                'db_table': 'directorates',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormDelegation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('delegated_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Delegacao de formulario',
                'verbose_name_plural': 'Delegacoes de formulario',
                'db_table': 'form_delegations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_external_id', models.UUIDField(blank=True, db_column='user_id', null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('setor', models.CharField(blank=True, max_length=120)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('finalized', 'Finalizado'), ('submitted', 'Enviado')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Relatorio mensal',
                'verbose_name_plural': 'Relatorios mensais',
                'db_table': 'monthly_reports',
                'ordering': ['-year', '-month', '-updated_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlySubmission',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Submissao mensal',
                'verbose_name_plural': 'Submissoes mensais',
                'db_table': 'submissions',
                'ordering': ['-year', '-month', '-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Osc',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(blank=True, max_length=120)),
                ('cep', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('subsidized_count', models.IntegerField(default=0)),
                ('objeto', models.TextField(blank=True)),
                ('objetivos', models.TextField(blank=True)),
                ('metas', models.TextField(blank=True)),
                ('atividades', models.TextField(blank=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'OSC',
                'verbose_name_plural': 'OSCs',
                'db_table': 'oscs',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendada'), ('completed', 'Concluida')], default='draft', max_length=20)),
                ('identificacao', models.JSONField(blank=True, null=True)),
                ('atendimento', models.JSONField(blank=True, null=True)),
                ('forma_acesso', models.JSONField(blank=True, null=True)),
                ('rh_data', models.JSONField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('recomendacoes', models.TextField(blank=True)),
                ('assinaturas', models.JSONField(blank=True, null=True)),
                ('parecer_tecnico', models.JSONField(blank=True, null=True)),
                ('parecer_conclusivo', models.JSONField(blank=True, null=True)),
                ('relatorio_final', models.JSONField(blank=True, null=True)),
                ('notificacoes', models.JSONField(blank=True, default=list)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('user_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Visita tecnica',
                'verbose_name_plural': 'Visitas tecnicas',
                'db_table': 'visits',
                'ordering': ['-visit_date', '-visit_time', '-updated_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('finalized', 'Finalizado'), ('submitted', 'Enviado')], default='draft', max_length=20)),
            ],
            options={
                'verbose_name': 'Plano de trabalho',
                'verbose_name_plural': 'Planos de trabalho',
                'db_table': 'work_plans',
                'ordering': ['-updated_at', 'title'],
                'managed': False,
            },
        ),
    ]
