# Generated by Django 5.2.1 on 2026-05-11 13:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrasReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_external_id', models.UUIDField(blank=True, db_column='user_id', null=True)),
                ('unit_name', models.TextField()),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('mes_anterior', models.IntegerField(blank=True, default=0, null=True)),
                ('admitidas', models.IntegerField(blank=True, default=0, null=True)),
                ('desligadas', models.IntegerField(blank=True, default=0, null=True)),
                ('atual', models.IntegerField(blank=True, default=0, null=True)),
                ('atendimentos', models.IntegerField(blank=True, default=0, null=True)),
                ('visita_domiciliar', models.IntegerField(blank=True, default=0, null=True)),
                ('atend_particularizado', models.IntegerField(blank=True, default=0, null=True)),
                ('pro_pao', models.IntegerField(blank=True, default=0, null=True)),
                ('dmae', models.IntegerField(blank=True, default=0, null=True)),
                ('auxilio_documento', models.IntegerField(blank=True, default=0, null=True)),
                ('cesta_basica', models.IntegerField(blank=True, default=0, null=True)),
                ('fralda', models.IntegerField(blank=True, default=0, null=True)),
                ('absorvente', models.IntegerField(blank=True, default=0, null=True)),
                ('bpc', models.IntegerField(blank=True, default=0, null=True)),
                ('carteirinha_idoso', models.IntegerField(blank=True, default=0, null=True)),
                ('passe_livre_deficiente', models.IntegerField(blank=True, default=0, null=True)),
                ('cadastros_novos', models.IntegerField(blank=True, default=0, null=True)),
                ('recadastros', models.IntegerField(blank=True, default=0, null=True)),
                ('rma_url', models.TextField(blank=True, null=True)),
                ('anexo_rma', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Relatorio CRAS',
                'verbose_name_plural': 'Relatorios CRAS',
                'db_table': 'cras_reports',
                'ordering': ['-year', '-month', 'unit_name', '-updated_at'],
                'managed': False,
            },
        ),
    ]
