# Generated by Django 5.2.1 on 2026-05-11 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiosReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_external_id', models.UUIDField(blank=True, db_column='user_id', null=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('encaminhadas_inclusao_cadunico', models.IntegerField(blank=True, default=0, null=True)),
                ('encaminhadas_atualizacao_cadunico', models.IntegerField(blank=True, default=0, null=True)),
                ('consulta_cadunico', models.IntegerField(blank=True, default=0, null=True)),
                ('numero_nis', models.IntegerField(blank=True, default=0, null=True)),
                ('dmae', models.IntegerField(blank=True, default=0, null=True)),
                ('pro_pao', models.IntegerField(blank=True, default=0, null=True)),
                ('auxilio_documento', models.IntegerField(blank=True, default=0, null=True)),
                ('carteirinha_idoso', models.IntegerField(blank=True, default=0, null=True)),
                ('bpc_presencial', models.IntegerField(blank=True, default=0, null=True)),
                ('bpc_online', models.IntegerField(blank=True, default=0, null=True)),
                ('solicitacao_colchoes', models.IntegerField(blank=True, default=0, null=True)),
                ('cesta_basica', models.IntegerField(blank=True, default=0, null=True)),
                ('solicitacao_fraldas', models.IntegerField(blank=True, default=0, null=True)),
                ('absorvente', models.IntegerField(blank=True, default=0, null=True)),
                ('agasalho_cobertor', models.IntegerField(blank=True, default=0, null=True)),
                ('visitas_cadunico', models.IntegerField(blank=True, default=0, null=True)),
                ('visita_nucleo_habitacao', models.IntegerField(blank=True, default=0, null=True)),
                ('visita_cesta_fraldas_colchoes', models.IntegerField(blank=True, default=0, null=True)),
                ('visita_dmae', models.IntegerField(blank=True, default=0, null=True)),
                ('visitas_pro_pao', models.IntegerField(blank=True, default=0, null=True)),
                ('total_visitas', models.IntegerField(blank=True, default=0, null=True)),
                ('busao_social_1', models.IntegerField(blank=True, default=0, null=True)),
                ('busao_social_2', models.IntegerField(blank=True, default=0, null=True)),
                ('dibs', models.IntegerField(blank=True, default=0, null=True)),
                ('familias_pbf', models.IntegerField(blank=True, default=0, null=True)),
                ('pessoas_cadunico', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Relatorio Beneficios',
                'verbose_name_plural': 'Relatorios Beneficios',
                'db_table': 'beneficios_reports',
                'ordering': ['-year', '-month', '-updated_at'],
                'managed': False,
            },
        ),
    ]
